window.APP_CONFIG = {
  SUPABASE_URL: "https://hklgsjozideopydbdcmp.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrbGdzam96aWRlb3B5ZGJkY21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MTg1OTUsImV4cCI6MjA4NTE5NDU5NX0.HqsGTto4CmExajUlq5ZzrzsctRCMDw6_-0XGKXZf7z4",
  REFRESH_INTERVAL: 0
};
